fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,6 +10,8 @@ on:
 
 permissions:
   contents: write
+  id-token: write
+  pages: write
 
 jobs:
   filter:
@@ -74,8 +76,8 @@ jobs:
       - name: Setup hugo cache
         uses: actions/cache@v4
         with:
-          path: ./exampleSite/resources
-          key: ${{ runner.os }}-hugo-${{ hashFiles('./exampleSite/resources') }}
+          path: ./resources
+          key: ${{ runner.os }}-hugo-${{ hashFiles('./resources') }}
           restore-keys: ${{ runner.os }}-hugo-
 
       - name: Install dependencies
@@ -84,8 +86,38 @@ jobs:
       - name: Build
         run: pnpm run build
 
+      - name: Upload build artifacts
+        uses: actions/upload-pages-artifact@v3
+        with:
+          name: github-pages
+          path: ./exampleSite/public
+
       - name: Push artifacts
-        if: ${{ (github.event_name == 'push' || github.event.pull_request.merged == true) && needs.filter.outputs.any_changed == 'true' }}
+        if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
           commit_message: 'ci: update bundled artifacts [skip ci]'
+
+      - name: Check for symlinks and hard links
+        run: |
+          if find ./exampleSite/public -type l | read; then
+            echo "Error: Symlinks found in the build artifacts" >&2
+            exit 1
+          fi
+
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Download build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: github-pages
+          path: ./public
+
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
